const biographyRu = `Ксения Попова - пианистка, коуч, музыкальный критик. В 2017 году окончила фортепианный факультет Санкт-Петербургской консерватории им. Н.А. Римского-Корсакова, сразу по окончанию стала концертмейстером студенческого хора СПбГУ. В 2021 году окончила магистерскую программу СПбГУ по направлению «Музыкальная критика». Магистерская диссертация написана и защищена на тему «Россини в России: аспекты исполнения (2000-2020 гг.). Концертмейстер кафедры хорового дирижирования института им. А. Герцена и Санкт-Петербургского института культуры. Ведёт частную практику как коуч: среди учеников - солисты театров Санкт-Петербурга, студенты и выпускники музыкальных ВУЗов и ССУЗов по вокалу и фортепиано. В августе 2018 года проходила стажировку “Settimana Rossiniana”в г. Мольфетта, Италия как концертмейстер (индивидуальная работа с вокалистами, подготовка вокалистов к концертным выступлениям, подготовка партий). В мае 2019 года прошла стажировку у Симонетты Танкреди (Италия) в г. Москва. В августе 2019 года стажировалась в г. Мольфетта в программе "Repertorio Verdiano".
Пианистка выступает на лучших концертных площадках России и за рубежом, помимо концертной деятельности Ксения ведет кураторскую деятельность: с  2014 по 2017 год курировала музыкальные мероприятия в Научно-исследовательском музее Академии художеств, а в 2020 и 2021 году провела конкурс фортепианного искусства Piano InstaCompetition, который собрал более сотни музыкантов профессионалов и любителей по всей России. Ведет блог в Инстаграме* и телеграм-канал «Разговоры за клавиром»

С января 2019 является членом Российской гильдии пианистов-концертмейстеров. `

const biographyEn = `Kseniia Popova is a pianist, concertmaster, coach and curator. A graduate of the Saint-Petersburg Conservatory in 2017,  Kseniia is currently working at the student’s choir of the St. Petersburg State University, at the choir conducting department at the Institute of Culture and Herzen University as concertmaster. During the summer of 2018 Kseniia completed an internship in Molfetta (Italy) about Rossini’s style, and Verdi’s style in summer of 2019. In the spring of 2019 Kseniia was improving her professional skills with the principal accompanist of the Theatre La Scala Simonetta Tancredi.
In 2014 Kseniia created her own curatorial project at the Museum of the Academy of Fine Arts, to help young musicians, students and alumni have performance practice. In 2018 Kseniia prepared and performed a “Misa Tango” of M. Palmeri with the principal conductor of the State University choir E. Krotman. In the same year, she prepared Rossini's opera “La Cenerentola” at the Small Philharmonic Hall. In 2021/2022 Kseniia prepared and performed jazz choir music by Will Todd with State University Choir (first performance in Russia).
In response to the pandemic, Kseniia created an online video competition “Piano InstaCompetition” held on Instagram, during which she created a new community that brought together professional musicians and amateurs throughout Russia. She is currently studying at Smolny, completing her MA degree in music criticism. In the future, Kseniia wants to make the “Piano InstaCompetition” international and create an Academy of Arts for the music community.`

export { biographyRu, biographyEn }
