import type { NextPage } from 'next'
import Head from 'next/head'
import styles from 'styles/Home.module.css'
import HomePage from '../components/homePage'

const Home: NextPage = () => {
    return (
        <div className={styles.container}>
            <Head>
                <title></title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <HomePage />

            <footer className={styles.footer}></footer>
        </div>
    )
}

export default Home
